name: Check
on:
  push:
    branches:
      - main
      - 'renovate/**'
  pull_request:

jobs:
  build-images:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'

    strategy:
      fail-fast: false # Ensures that if one build fails, the others will still run
      matrix:
        include:
          - path: "adk/python/weather-agent"
          - path: "adk/python/delegate-agent"
          - path: "wiremock/mock-agent"

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v5'
        with:
          fetch-depth: 0 # required to fetch all history for all branches and tags

      - name: 'Docker Build'
        working-directory: ${{ matrix.path }}
        run: |
          make docker-build
