name: Push
on:
  push:
    branches: [ main ]

env:
  GCP_LOCATION: 'europe-west3'
  GCP_PROJECT_ID: 'qaware-paal'
  GCP_REPOSITORY: 'agentic-layer'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/387309373030/locations/global/workloadIdentityPools/github-actions-identity-pool/providers/github-actions-provider'
  SERVICE_ACCOUNT: 'sa-github-actions@qaware-paal.iam.gserviceaccount.com'

jobs:
  push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    strategy:
      fail-fast: false # Ensures that if one build fails, the others will still run
      matrix:
        include:
          - path: "adk/python/weather-agent"

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0 # required to fetch all history for all branches and tags

      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: 'Configure Docker for Artifact Registry'
        run: gcloud auth configure-docker ${{ env.GCP_LOCATION }}-docker.pkg.dev

      - name: 'Docker Push'
        working-directory: ${{ matrix.path }}
        run: |
          make docker-push
