name: Push
on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      packages: 'write'

    strategy:
      fail-fast: false # Ensures that if one build fails, the others will still run
      matrix:
        include:
          - name: "weather-agent"
            path: "adk/python/weather-agent"
          - name: "delegate-agent"
            path: "adk/python/delegate-agent"

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v5'
        with:
          fetch-depth: 0 # required to fetch all history for all branches and tags

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Docker Build & Push'
        working-directory: ${{ matrix.path }}
        run: |
          make docker-push
